name: Create Release and Build Executables

on:
  push:
    tags:
      - 'v*' # v로 시작하는 태그가 푸시되면 이 워크플로우가 실행됩니다 (예: v1.0, v1.1)

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }} # macOS와 Windows에서 각각 실행됩니다
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build with PyInstaller (macOS)
        if: runner.os == 'macOS'
        run: |
          pyinstaller main.py \
            --name "Loadcell-Viewer" \
            --windowed \
            --add-data "utils:utils" \
            --add-data "config.json:." \
            --add-data "calibration.json:."

      - name: Build with PyInstaller (Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller main.py `
            --name "Loadcell-Viewer" `
            --windowed `
            --add-data "utils;utils" `
            --add-data "config.json;." `
            --add-data "calibration.json;."

      - name: Package build artifacts
        run: |
          if [ "${{ runner.os }}" == "macOS" ]; then
            zip -r Loadcell-Viewer-macOS.zip dist/Loadcell-Viewer.app
          elif [ "${{ runner.os }}" == "Windows" ]; then
            7z a -tzip Loadcell-Viewer-Windows.zip ./dist/Loadcell-Viewer/*
          fi
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-artifact
          path: ./*.zip

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/macOS-artifact/*.zip
            artifacts/Windows-artifact/*.zip