name: Create Release and Build Executables

on:
  push:
    tags:
      - 'v*' # v로 시작하는 태그가 푸시되면 이 워크플로우가 실행됩니다 (예: v1.0, v1.1)

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }} # macOS와 Windows에서 각각 실행됩니다
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build with PyInstaller (macOS)
        if: runner.os == 'macOS'
        run: |
          pyinstaller main.py \
            --name "Loadcell-Viewer" \
            --onefile \
            --windowed \
            --add-data "utils:utils"

      - name: Build with PyInstaller (Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller main.py `
            --name "Loadcell-Viewer" `
            --onefile `
            --windowed `
            --add-data "utils;utils"
      
      - name: Prepare macOS Artifact
        if: runner.os == 'macOS'
        run: zip -r Loadcell-Viewer-macOS.zip dist/Loadcell-Viewer.app

      - name: Upload macOS Artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifact
          path: Loadcell-Viewer-macOS.zip

      - name: Upload Windows Artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: dist/Loadcell-Viewer.exe

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build # 모든 'build' 작업이 성공해야만 실행됩니다
    permissions:
      contents: write # 릴리즈를 생성하기 위해 필수적인 권한입니다

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts # 아티팩트를 artifacts 폴더에 다운로드합니다

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/macos-artifact/*
            artifacts/windows-artifact/*